"""Python<->Dart write-contract test: asserts compute_register_writes reproduces
the Dart applier output for every write golden vector (Task 7, SP-C).

The vendored file at tests/fixtures/write-golden-vectors.json is the ground
truth generated by the Dart reference write-applier. If a vector mismatches,
fix write_compute.py or register_spec.py — not this test or the vectors."""
import json
import pathlib

from custom_components.svitgrid.harvest.register_spec import WriteCommand
from custom_components.svitgrid.harvest.write_compute import compute_register_writes

VECTORS = pathlib.Path(__file__).parent.parent / "fixtures" / "write-golden-vectors.json"


def _load() -> dict:
    return json.loads(VECTORS.read_text())


def test_python_writes_match_dart_applier_for_every_vector() -> None:
    data = _load()
    assert data["vectors"], "no vectors"
    for v in data["vectors"]:
        cmd = WriteCommand.from_dict(v["writeCommand"])
        prior = {int(a): w for a, w in v.get("priorRegisters", {}).items()}
        got = compute_register_writes(cmd, v["payload"], prior)
        exp = [(x["unitId"], x["address"], x["value"]) for x in v["expectedRegisterWrites"]]
        assert got == exp, (
            f"{v['modelId']}/{v['command']}: got {got} != expected {exp}"
        )


def test_vendored_write_vectors_have_source_commit() -> None:
    assert _load().get("sourceCommit"), (
        "write-golden-vectors.json missing sourceCommit header"
    )
