"""Python<->Dart contract test: asserts the Python decoder reproduces the Dart
reader output for every golden vector (Task 5, SP-B).

The vendored file at tests/fixtures/golden-vectors.json is the ground truth
generated by the Dart reference reader via export_golden_vectors.dart. If a
field mismatches, fix decoder.py — not this test."""

import json
import math
import pathlib

from custom_components.svitgrid.harvest.decoder import decode, sanitize
from custom_components.svitgrid.harvest.register_spec import RegisterSpec

VECTORS = pathlib.Path(__file__).parent.parent / "fixtures" / "golden-vectors.json"


def _load() -> dict:
    return json.loads(VECTORS.read_text())


def _raw(d: dict) -> dict[int, dict[int, int]]:
    return {int(u): {int(a): w for a, w in addrs.items()} for u, addrs in d.items()}


def test_python_decoder_matches_dart_reader_for_every_vector() -> None:
    data = _load()
    assert data["vectors"], "no vectors"
    for v in data["vectors"]:
        spec = RegisterSpec.from_dict(v["spec"])
        out = sanitize(decode(spec, _raw(v["rawRegisters"])), spec)
        for field, expected in v["expectedFields"].items():
            actual = out.get(field)
            if expected is None:
                assert actual is None, f"{v['modelId']}.{field}: expected None, got {actual}"
            else:
                assert actual is not None, f"{v['modelId']}.{field}: expected {expected}, got None"
                assert math.isclose(actual, expected, abs_tol=1e-6), (
                    f"{v['modelId']}.{field}: {actual} != {expected}"
                )


def test_vendored_vectors_have_source_commit() -> None:
    sc = _load().get("sourceCommit")
    assert sc, "golden-vectors.json missing sourceCommit header"
    assert sc != "dev", "pin sourceCommit to a real main-repo sha so drift is detectable"


# ---------------------------------------------------------------------------
# Coverage guards. The 2026-08-17 gap class (two missing builtins, an ignored
# lowWordFirst, an ignored FC04) was invisible for seven weeks because the
# vendored vectors covered only the Deye family. A regeneration that silently
# drops these classes must fail here rather than in the field.
# ---------------------------------------------------------------------------


def _specs() -> list[dict]:
    return [v["spec"] for v in _load()["vectors"]]


def test_vectors_cover_every_builtin_the_corpus_uses() -> None:
    used = {
        d["builtin"] for s in _specs() for d in s.get("derivations", []) if d.get("op") == "builtin"
    }
    for name in ("grid_sign_normalize", "battery_power_from_vi"):
        assert name in used, f"no vector exercises the {name} builtin"


def test_vectors_cover_a_low_word_first_read() -> None:
    assert any(r.get("lowWordFirst") for s in _specs() for r in s.get("reads", [])), (
        "no vector exercises a lowWordFirst 32-bit read (Megarevo)"
    )


def test_vectors_cover_an_fc04_model() -> None:
    assert any(r.get("functionCode") == "FC04" for s in _specs() for r in s.get("reads", [])), (
        "no vector exercises an FC04 (input-register) model (Afore/KSTAR/Solis)"
    )


def test_every_vendored_spec_validates() -> None:
    """validate() must be clean for the whole vendored corpus — this is exactly
    the check __init__/config_flow now run at spec load time."""
    for v in _load()["vectors"]:
        problems = RegisterSpec.from_dict(v["spec"]).validate()
        assert problems == [], f"{v['modelId']}: {problems}"
