"""Python<->Dart contract test: asserts the Python decoder reproduces the Dart
reader output for every golden vector (Task 5, SP-B).

The vendored file at tests/fixtures/golden-vectors.json is the ground truth
generated by the Dart reference reader via export_golden_vectors.dart. If a
field mismatches, fix decoder.py — not this test."""
import json
import math
import pathlib

from custom_components.svitgrid.harvest.decoder import decode, sanitize
from custom_components.svitgrid.harvest.register_spec import RegisterSpec

VECTORS = pathlib.Path(__file__).parent.parent / "fixtures" / "golden-vectors.json"


def _load() -> dict:
    return json.loads(VECTORS.read_text())


def _raw(d: dict) -> dict[int, dict[int, int]]:
    return {int(u): {int(a): w for a, w in addrs.items()} for u, addrs in d.items()}


def test_python_decoder_matches_dart_reader_for_every_vector() -> None:
    data = _load()
    assert data["vectors"], "no vectors"
    for v in data["vectors"]:
        spec = RegisterSpec.from_dict(v["spec"])
        out = sanitize(decode(spec, _raw(v["rawRegisters"])), spec)
        for field, expected in v["expectedFields"].items():
            actual = out.get(field)
            if expected is None:
                assert actual is None, (
                    f"{v['modelId']}.{field}: expected None, got {actual}"
                )
            else:
                assert actual is not None, (
                    f"{v['modelId']}.{field}: expected {expected}, got None"
                )
                assert math.isclose(actual, expected, abs_tol=1e-6), (
                    f"{v['modelId']}.{field}: {actual} != {expected}"
                )


def test_vendored_vectors_have_source_commit() -> None:
    assert _load().get("sourceCommit"), "golden-vectors.json missing sourceCommit header"
